flowchart TD
    subgraph Pirate.Shell
        Program --> Application
        Application -- args --> CommandManager

        subgraph Command
            CommandManager --Run--> CommandFactory
            RunCommand -- run --> BuildCommand
            
            CommandFactory --run--> RunCommand
            CommandFactory --run--> BuildCommand
            CommandFactory --run--> ShellCommand
            CommandFactory --run--> InitCommand
            CommandFactory --run--> NewCommand
            
            

        end        
    end
    
    subgraph Pirate.Shell.Modules
        BuildCommand --GetList--> ModuleListRepostory
    end

    subgraph Pirate.Lexer
        BuildCommand --MakeTokens--> Lexer
        ShellCommand --MakeTokens--> Lexer

        Lexer --> Token
    end

    subgraph Pirate.Parser
        BuildCommand --StartParse--> Parser
        ShellCommand --StartParse--> Parser

        Parser --> ParserTree
    end

    subgraph Pirate.Interpreter
        ShellCommand --StartInterpreter--> Interpreter
        RunCommand --StartInterpreter--> Interpreter

        Interpreter --> InterpreterTree
    end

    subgraph Pirate.Common.FileHandler
        InitCommand --WriteToFile--> FileWriteHandler
        NewCommand --WriteToFile--> FileWriteHandler
        ModuleListRepostory --WriteToFile--> FileWriteHandler

        ModuleListRepostory --ReadAllFile--> FileReadHandler
        BuildCommand --ReadAllFile--> FileReadHandler

    end
