<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pirate.Lexer\Pirate.Lexer.csproj" />
    <ProjectReference Include="..\Pirate.Parser\Pirate.Parser.csproj" />
    <ProjectReference Include="..\Pirate.Semantics\Pirate.Semantics.csproj" />
    <ProjectReference Include="..\Pirate.Compiler\Pirate.Compiler.csproj" />
    <ProjectReference Include="..\Pirate.VM\Pirate.VM.csproj" />
    <ProjectReference Include="..\Pirate.StandardLibrary\Pirate.StandardLibrary.csproj" />
    <ProjectReference Include="..\Pirate.Shared.File\Pirate.Shared.File.csproj" />
    <ProjectReference Include="..\Pirate.Fleet\Pirate.Fleet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.0-alpha</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pirate.Cli.Test" />
  </ItemGroup>

</Project>
