namespace PirateLexer.Models
{
    public enum TokenType
    {
        INT,
        FLOAT,
        STRING,
        IDENTIFIER,
        KEYWORD,
        PLUS,
        MINUS,
        MULTIPLY,
        DIVIDE,
        EQUALS,
        LEFTPARENTHESES,
        RIGHTPARENTHESES,
        ENDOFFILE,
        ENDOFLINE,
        POWER,
        DOUBLEEQUALS,
        NOTEQUALS,
        LESSTHAN,
        GREATHERTHAN,
        LESSTHANEQUALS,
        GREATERTHANEQUALS,
        COMMA,
        COLON,
        RIGHTCURLYBRACE,
        LEFTCURLYBRACE
    }
}