<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="8.11.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Reqnroll.xUnit" Version="3.3.4" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pirate.Lexer\Pirate.Lexer.csproj" />
    <ProjectReference Include="..\Pirate.Parser\Pirate.Parser.csproj" />
    <ProjectReference Include="..\Pirate.Semantics\Pirate.Semantics.csproj" />
    <ProjectReference Include="..\Pirate.Compiler\Pirate.Compiler.csproj" />
    <ProjectReference Include="..\Pirate.VM\Pirate.VM.csproj" />
    <ProjectReference Include="..\Pirate.StandardLibrary\Pirate.StandardLibrary.csproj" />
    <ProjectReference Include="..\Pirate.Cli\Pirate.Cli.csproj" />
  </ItemGroup>

</Project>
