flowchart TD
    subgraph Pirate.Shell
        Program --> Application
        Application -- args --> CommandManager

        subgraph Command
            CommandManager --Run--> CommandFactory
            RunCommand -- run --> BuildCommand
            
            CommandFactory --run--> RunCommand
            CommandFactory --run--> BuildCommand
            CommandFactory --run--> ShellCommand
            CommandFactory --run--> InitCommand
            CommandFactory --run--> NewCommand
            
        end        
    end
    
    subgraph Pirate.Shell.Modules
        BuildCommand --GetList--> ModuleListRepostory
    end

    subgraph Pirate.Lexer
        BuildCommand --MakeTokens--> Lexer
        ShellCommand --MakeTokens--> Lexer

        Lexer --> TokenRepository
        Lexer --> TokenResult

        TokenRepository --- Token
        TokenRepository --> KeyWordService
        TokenRepository --> TokenResult

        TokenResult --> Token

        Token --- TokenType
        Token --- TokenGroup
    end

    subgraph Pirate.Parser
        ParserFactory[ParserFactory]
        FunctionDeclarationParser[FunctionDeclarationParser]
        IfStatementParser[IfStatementParser]
        ForLoopStatementParser[ForLoopStatementParser]
        WhileLoopStatementParser[WhileLoopStatementParser]
        VariableDeclarationParser[VariableDeclarationParser]
        IdentifierParser[IdentifierParser]
        OperationParser[OperationParser]
        CommentParser[CommentParser]

        subgraph Nodes
            Node[Node]
            OperationNode[OperationNode]

            BinaryOperationNode[BinaryOperationNode]
            CommentNode[CommentNode]
            ComparisonOperationNode[ComparisonOperationNode]
            ForLoopStatementNode[ForLoopStatementNode]
            FunctionCallNode[FunctionCallNode]
            FunctionDeclarationNode[FunctionDeclarationNode]
            IfStatementNode[IfStatementNode]
            ParameterDefinitionNode[ParameterDefinitionNode]
            ValueNode[ValueNode]
            VariableAssignmentNode[VariableAssignmentNode]
            VariableDeclarationNode[VariableDeclarationNode]
            WhileLoopStatementNode[WhileLoopStatementNode]
		end

        BuildCommand --StartParse--> Parser
        ShellCommand --StartParse--> Parser

        Parser --> ParserFactory
        ParserFactory --- CommentParser
        ParserFactory --- ForLoopStatementParser
        ParserFactory --- FunctionDeclarationParser
        ParserFactory --- IdentifierParser
        ParserFactory --- IfStatementParser
        ParserFactory --- OperationParser
        ParserFactory --- VariableDeclarationParser
        ParserFactory --- WhileLoopStatementParser

        ForLoopStatementParser --> ParserFactory
        FunctionDeclarationParser --> ParserFactory
        IdentifierParser --> ParserFactory
        IfStatementParser --> ParserFactory
        VariableDeclarationParser --> ParserFactory
        WhileLoopStatementParser --> ParserFactory

		CommentParser --> CommentNode
	    ForLoopStatementParser --> ForLoopStatementNode
        FunctionDeclarationParser --> FunctionDeclarationNode
        IdentifierParser --> OperationParser
        IdentifierParser --> VariableAssignmentNode
        IdentifierParser --> FunctionCallNode
        IfStatementParser --> IfStatementNode
		OperationParser --> ComparisonOperationNode
        OperationParser --> BinaryOperationNode
        OperationParser --> ValueNode
        VariableDeclarationParser --> OperationParser
        VariableDeclarationParser --> VariableDeclarationNode
        WhileLoopStatementParser --> WhileLoopStatementNode


        Node --- ParseResult
        OperationNode --- ParseResult

        BinaryOperationNode --- ParseResult
        BinaryOperationNode --> Node
        BinaryOperationNode --> Token

        CommentNode --- ParseResult
        CommentNode ==> Token

        ComparisonOperationNode --- ParseResult
        ComparisonOperationNode --> Node
        ComparisonOperationNode --> Token

        ForLoopStatementNode --- ParseResult
        ForLoopStatementNode --> VariableDeclarationNode
        ForLoopStatementNode --> ValueNode
        ForLoopStatementNode ==> Node

        FunctionCallNode --- ParseResult
        FunctionCallNode --> ValueNode
        FunctionCallNode ==> Node

        FunctionDeclarationNode --- ParseResult
        FunctionDeclarationNode --> ValueNode
        FunctionDeclarationNode ==> ParameterDefinitionNode
        FunctionDeclarationNode --> Token 
        FunctionDeclarationNode ==> Node

        IfStatementNode --- ParseResult
        IfStatementNode --> OperationNode
        IfStatementNode ==> Node

        ParameterDefinitionNode --- ParseResult
        ParameterDefinitionNode --> Token
        ParameterDefinitionNode --> ValueNode

        ValueNode --- ParseResult
        ValueNode --> Token

        VariableAssignmentNode --- ParseResult
        VariableAssignmentNode --> ValueNode
        VariableAssignmentNode --> Node

		VariableDeclarationNode --- ParseResult
        VariableDeclarationNode --> Token
        VariableDeclarationNode --> ValueNode
        VariableDeclarationNode --> Node

        WhileLoopStatementNode --- ParseResult
        WhileLoopStatementNode --> OperationNode
        WhileLoopStatementNode ==> Node


        ParseResult --AddNode--> Scope
    end

    subgraph Pirate.Interpreter
        ShellCommand --StartInterpreter--> Interpreter
        RunCommand --StartInterpreter--> Interpreter

        Interpreter --GetInterpreter--> InterpreterFactory

        InterpreterFactory --- BinaryOperationInterpreter
        InterpreterFactory --- CommentInterpreter
        InterpreterFactory --- ComparisonOperationInterpreter
        InterpreterFactory --- ForLoopStatementInterpreter
        InterpreterFactory --- FunctionCallInterpreter
        InterpreterFactory --- FunctionDeclarationInterpreter
        InterpreterFactory --- IfStatementInterpreter
        InterpreterFactory --- ValueInterpreter
        InterpreterFactory --- VariableAssignmentInterpreter
        InterpreterFactory --- VariableDeclarationInterpreter
        InterpreterFactory --- WhileLoopStatementInterpreter

        subgraph BaseValue
            BooleanValue[BooleanValue]
            CharValue[CharValue]
            FloatValue[FloatValue]
            FunctionValue[FunctionValue]
            IntegerValue[IntegerValue]
            Library[Library]
            StringValue[StringValue]
            VariableValue[VariableValue]
        end

        subgraph StandardLibrary
            StandardLibraryCallManager[StandardLibraryCallManager]
		end

        BinaryOperationInterpreter --> InterpreterFactory
        BinaryOperationInterpreter --> BaseValue

        CommentInterpreter --> InterpreterFactory
        CommentInterpreter --> BaseValue

        ComparisonOperationInterpreter --> InterpreterFactory
        ComparisonOperationInterpreter --> BooleanValue

        ForLoopStatementInterpreter --> InterpreterFactory
        ForLoopStatementInterpreter --> BaseValue
        ForLoopStatementInterpreter --> VariableValue
        ForLoopStatementInterpreter --> IntegerValue

        FunctionCallInterpreter --> StandardLibraryCallManager
        FunctionCallInterpreter --> InterpreterFactory
        FunctionCallInterpreter --> BaseValue
        FunctionCallInterpreter --> FunctionValue
        FunctionCallInterpreter --> Library

        FunctionDeclarationInterpreter --> InterpreterFactory
        FunctionDeclarationInterpreter --> BaseValue
        FunctionDeclarationInterpreter --> FunctionValue

        IfStatementInterpreter --> InterpreterFactory
        IfStatementInterpreter --> BaseValue
        IfStatementInterpreter --> BooleanValue

        ValueInterpreter --> InterpreterFactory
        ValueInterpreter --> BaseValue
        ValueInterpreter --> IntegerValue
        ValueInterpreter --> StringValue
        ValueInterpreter --> CharValue
        ValueInterpreter --> FloatValue
        ValueInterpreter --> VariableValue

        VariableAssignmentInterpreter --> InterpreterFactory
        VariableAssignmentInterpreter --> BaseValue

        VariableDeclarationInterpreter --> InterpreterFactory
        VariableDeclarationInterpreter --> BaseValue
        VariableDeclarationInterpreter --> VariableValue

        WhileLoopStatementInterpreter --> InterpreterFactory
        WhileLoopStatementInterpreter --> BaseValue
        WhileLoopStatementInterpreter --> BooleanValue
    end

    subgraph Pirate.Common
        Parser --SerializeObject--> ObjectSerializer
        Interpreter --Deserialize--> ObjectSerializer
    end

    subgraph Pirate.Common.FileHandler
        InitCommand --WriteToFile--> FileWriteHandler
        NewCommand --WriteToFile--> FileWriteHandler
        ModuleListRepostory --WriteToFile--> FileWriteHandler

        ModuleListRepostory --ReadAllFile--> FileReadHandler
        BuildCommand --ReadAllFile--> FileReadHandler

    end
